name: "Set PR labels based on PR title"
description: "Set PR label based on PR title's pattern"
author: TDAK <dbcgdhh@gmail.com>

inputs:
  words:
    description: "Array of words which PR title contains"
    required: true
  labels:
    description: "Array of labels, if PR title contains words[i], apply label[i]"
    required: true
  repo-token:
    description: "Repo GITHUB_TOKEN"
    required: true

branding:
  icon: "tag"
  color: "yellow"

runs:
  using: "node12"
  main: "index.js"
